// 40 testimonials: 25 identified with Unsplash images, 15 anonymous with initials
// Each item: { id, name, text, categories[], rating, imageUrl?, anonymous }
// Note: Images sourced from Unsplash random endpoints with specific topics to avoid PII; cache-busted via id.

window.GB_TESTIMONIALS = [
  // Identified (25)
  { id: 1,  name: 'Lucas Almeida', text: 'I tried every plan on my own and kept quitting after two weeks. Andre gave me structure, habits I could actually follow and honest feedback. I lost inches from my waist and, more importantly, I feel capable again.', categories: ['weight-loss','transformation','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?auto=format&fit=crop&w=300&q=60' },
  { id: 2,  name: 'Daniela Castro', text: 'I appreciate the honest, data-driven approach. No gimmicks—just a plan tailored to me that I could actually follow.', categories: ['lifestyle','health','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=60' },
  { id: 3,  name: 'Noah Williams', text: 'Sleep, stress, and steps became part of the plan. The holistic view is what finally made my results stick.', categories: ['lifestyle','health','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=60' },
  { id: 4,  name: 'Lucia Martinez', text: 'After two pregnancies I thought my body wouldn’t respond. With gentle progressions and nutrition coaching, I’m stronger and more confident than before.', categories: ['weight-loss','health','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=60' },
  { id: 5,  name: 'Arjun Mehta', text: 'The technique cues on videos changed everything. I added 20kg to my squat while fixing depth and my knees feel great.', categories: ['muscle-gain','performance','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=300&q=60' },
  { id: 6,  name: 'Sophie Dubois', text: 'Travel used to derail me. Now I land, check the plan and keep momentum. The flexibility is the reason I finally stayed consistent.', categories: ['lifestyle','transformation','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=60' },
  { id: 7,  name: 'Chi Nguyen', text: 'My blood pressure normalized and I have energy after work. Small daily habits were the difference maker for me.', categories: ['health','lifestyle','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544006659-f0b21884ce1d?auto=format&fit=crop&w=300&q=60' },
  { id: 8,  name: 'Mateo Gonzalez', text: 'I lost 11kg without cutting entire food groups. The balanced approach removed the guilt and made weekends manageable.', categories: ['transformation','weight-loss','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=300&q=60' },
  { id: 9,  name: 'Ana Morales', text: 'We fixed my shoulder impingement while building my first pull-up. Coaching is detailed and encouraging at the same time.', categories: ['muscle-gain','health','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=300&q=60' },
  { id:10,  name: 'Jonas Muller', text: 'The accountability made me show up even on tough weeks. I built routines that finally feel automatic.', categories: ['lifestyle','health','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1541534401786-2077eed87a72?auto=format&fit=crop&w=300&q=60' },
  { id:11,  name: 'Peter Okoye', text: 'Conditioning improved for football season without burning me out. The plan fits around school and part-time work.', categories: ['performance','conditioning','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1546525848-3ce03ca516f6?auto=format&fit=crop&w=300&q=60' },
  { id:12,  name: 'Emma Johansson', text: 'I finally enjoy cooking again. The weekly recipes and shopping lists took away decision fatigue and helped me stay on track.', categories: ['weight-loss','health','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544005316-04ce1f9c9e07?auto=format&fit=crop&w=300&q=60' },
  { id:13,  name: 'Ahmed Hassan', text: 'Lean bulk done right. I gained size with minimal fat and learned to manage phases with clear targets.', categories: ['muscle-gain','transformation','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&w=300&q=60' },
  { id:14,  name: 'Zara Ali', text: 'Sleep hygiene and step goals were the game changers. I feel calm, productive, and my body reflects that.', categories: ['health','lifestyle','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1531123414780-f7424c28fad5?auto=format&fit=crop&w=300&q=60' },
  { id:15,  name: 'Mina Patel', text: 'Started for aesthetics, stayed for the confidence. The check-ins made me feel seen and supported every week.', categories: ['transformation','lifestyle','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=60' },
  { id:16,  name: 'James Walker', text: "As a busy dad I didn't think I had time. Andre simplified training and I stuck with it.", categories: ['weight-loss','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=300&q=60' },
  { id:17,  name: 'Thiago Pereira', text: 'I used to hide in baggy clothes. Twelve weeks later my friends keep asking what changed.', categories: ['transformation','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=300&q=60' },
  { id:18,  name: 'Sofia Martins', text: "Nutrition was always my struggle. Andre's flexible approach removed guilt.", categories: ['health','weight-loss','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544005316-04ce1f9c9e07?auto=format&fit=crop&w=300&q=60' },
  { id:19,  name: 'Gustavo Rocha', text: 'Came in with knee pain and fear of squats. We rebuilt technique and I got stronger pain-free.', categories: ['performance','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=300&q=60' },
  { id:20,  name: 'Isabela Nunes', text: 'I never imagined online coaching could feel this personal. The weekly video reviews made the difference.', categories: ['transformation','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544005316-04ce1f9c9e07?auto=format&fit=crop&w=300&q=60' },
  { id:21,  name: 'Carlos Mendes', text: 'Dropped 8kg and kept muscle. The plan felt realistic with my work schedule.', categories: ['weight-loss','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=60' },
  { id:22,  name: 'Laura Kim', text: 'Better energy and mood. The small habits added up.', categories: ['health','lifestyle','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=300&q=60' },
  { id:23,  name: 'Omar Farouk', text: 'Structured lifting got me past the plateau.', categories: ['muscle-gain','performance','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1546525848-3ce03ca516f6?auto=format&fit=crop&w=300&q=60' },
  { id:24,  name: 'Elena Petrova', text: 'Busy schedule friendly and effective.', categories: ['lifestyle','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=60' },
  { id:25,  name: 'Hiro Tanaka', text: 'Strength up, aches down. Great cues.', categories: ['performance','identified'], rating: 5, imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=60' },

  // Anonymous (15)
  { id:26, name: 'Anonymous', text: 'Finally consistent after years of stops and starts.', categories: ['anonymous','lifestyle'], rating: 5 },
  { id:27, name: 'Anonymous', text: 'Clothes fit better and I feel lighter.', categories: ['anonymous','weight-loss'], rating: 5 },
  { id:28, name: 'Anonymous', text: 'Back pain gone, technique improved.', categories: ['anonymous','health'], rating: 5 },
  { id:29, name: 'Anonymous', text: 'Meal plan that works for me.', categories: ['anonymous','health'], rating: 5 },
  { id:30, name: 'Anonymous', text: 'Gained my first 5 pull-ups!', categories: ['anonymous','muscle-gain'], rating: 5 },
  { id:31, name: 'Anonymous', text: 'Down 7kg in 12 weeks without extremes.', categories: ['anonymous','weight-loss'], rating: 5 },
  { id:32, name: 'Anonymous', text: 'Better sleep and focus at work.', categories: ['anonymous','health','lifestyle'], rating: 5 },
  { id:33, name: 'Anonymous', text: 'Stopped fearing carbs. Performance is up.', categories: ['anonymous','performance'], rating: 5 },
  { id:34, name: 'Anonymous', text: 'Program fits my travel schedule.', categories: ['anonymous','lifestyle'], rating: 5 },
  { id:35, name: 'Anonymous', text: 'Less joint pain, stronger lifts.', categories: ['anonymous','performance','health'], rating: 5 },
  { id:36, name: 'Anonymous', text: 'Confidence improved with visible progress.', categories: ['anonymous','transformation'], rating: 5 },
  { id:37, name: 'Anonymous', text: 'Simple habits that actually stick.', categories: ['anonymous','lifestyle'], rating: 5 },
  { id:38, name: 'Anonymous', text: 'From 0 to enjoying training.', categories: ['anonymous','transformation'], rating: 5 },
  { id:39, name: 'Anonymous', text: 'Doctor is happy with my lab results.', categories: ['anonymous','health'], rating: 5 },
  { id:40, name: 'Anonymous', text: 'Lean mass up, waist down.', categories: ['anonymous','muscle-gain','weight-loss'], rating: 5 }
];
