// 27 existing testimonials plus 10 transformation-photo client stories.
// Each item: { id, name, text, textKey?, categories[], rating, imageUrl?, result?, source?, avatarCrop?, avatarPosition?, avatarSize? }

window.GB_GOOGLE_REVIEW_SUMMARY = {
  rating: '5.0',
  count: 25,
  label: 'Rated 5.0 on Google',
  source: 'Google Reviews'
};

window.GB_TESTIMONIALS = [
  // Existing identified testimonials (17)
  { id: 1, name: "Conrad NorNam", textKey: "testimonial.conrad", text: "Andre rebuilt my training around 60-hour workweeks. We dropped 9kg of fat, added lean muscle, and my shoulders are pain-free for the first time in years.", categories: ["body-recomp", "muscle-gain", "identified"], rating: 5, imageUrl: "assets/images/transformations/conrad-before.jpg", avatarCrop: true, avatarPosition: "73% 21%", avatarSize: "265%" },
  { id: 2, name: "Lucas Almeida", textKey: "testimonial.lucas", text: "I tried every plan on my own and kept quitting after two weeks. Andre gave me structure, habits I could actually follow and honest feedback. I lost inches from my waist and, more importantly, I feel capable again.", categories: ["weight-loss", "transformation", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=300&h=300&fit=crop" },
  { id: 3, name: "Noah Williams", textKey: "testimonial.noah", text: "Sleep, stress, and steps became part of the plan. The holistic view is what finally made my results stick.", categories: ["lifestyle", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop" },
  { id: 4, name: "Arjun Mehta", textKey: "testimonial.arjun", text: "The technique cues on videos changed everything. I added 20kg to my squat while fixing depth and my knees feel great.", categories: ["muscle-gain", "performance", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=300&h=300&fit=crop" },
  { id: 5, name: "Mateo Gonzalez", textKey: "testimonial.mateo", text: "I lost 11kg without cutting entire food groups. The balanced approach removed the guilt and made weekends manageable.", categories: ["transformation", "weight-loss", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop" },
  { id: 6, name: "Jonas Muller", textKey: "testimonial.jonas", text: "The accountability made me show up even on tough weeks. I built routines that finally feel automatic.", categories: ["lifestyle", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop" },
  { id: 7, name: "James Walker", textKey: "testimonial.james", text: "As a busy dad I did not think I had time. Andre simplified training and I stuck with it.", categories: ["weight-loss", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop" },
  { id: 8, name: "Thiago Pereira", textKey: "testimonial.thiago", text: "I used to hide in baggy clothes. Twelve weeks later my friends keep asking what changed.", categories: ["transformation", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1531891570158-e71b35a485bc?w=300&h=300&fit=crop" },
  { id: 9, name: "Daniela Castro", textKey: "testimonial.daniela", text: "I appreciate the honest, data-driven approach. No gimmicks, just a plan tailored to me that I could actually follow.", categories: ["lifestyle", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop" },
  { id: 10, name: "Lucia Martinez", textKey: "testimonial.lucia", text: "After two pregnancies I thought my body would not respond. With gentle progressions and nutrition coaching, I am stronger and more confident than before.", categories: ["weight-loss", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop" },
  { id: 11, name: "Sophie Dubois", textKey: "testimonial.sophie", text: "Travel used to derail me. Now I land, check the plan and keep momentum. The flexibility is the reason I finally stayed consistent.", categories: ["lifestyle", "transformation", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop" },
  { id: 12, name: "Chi Nguyen", textKey: "testimonial.chi", text: "My blood pressure normalized and I have energy after work. Small daily habits were the difference maker for me.", categories: ["health", "lifestyle", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=300&h=300&fit=crop" },
  { id: 13, name: "Ana Morales", textKey: "testimonial.ana", text: "We fixed my shoulder impingement while building my first pull-up. Coaching is detailed and encouraging at the same time.", categories: ["muscle-gain", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop" },
  { id: 14, name: "Emma Johansson", textKey: "testimonial.emma", text: "I finally enjoy cooking again. The weekly recipes and shopping lists took away decision fatigue and helped me stay on track.", categories: ["weight-loss", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=300&fit=crop" },
  { id: 15, name: "Sofia Martins", textKey: "testimonial.sofia", text: "Nutrition was always my struggle. Andre flexible approach removed guilt.", categories: ["health", "weight-loss", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=300&h=300&fit=crop" },
  { id: 26, name: "Ana Paula", text: "Ana Paula completed a focused three-month transformation, losing 10kg through structured training, practical nutrition targets, and consistent weekly accountability. She also rebuilt her energy, confidence, and a routine she could sustain.", categories: ["weight-loss", "transformation", "lifestyle", "identified"], rating: 5 },
  { id: 27, name: "Isabella", text: "Across two years of coaching, Isabella achieved a complete body recomposition through personalised training, intelligent progression, recovery, and long-term consistency - building lean muscle, strength, confidence, and control over her training.", categories: ["transformation", "muscle-gain", "performance", "identified"], rating: 5 },

  // Transformation-photo additions (10)
  { id: 28, name: "Paulo D.", text: "Six months gave me enough time to stop rushing and actually learn the process. The plan was simple to repeat, the check-ins kept me focused, and 15kg came off without cutting out my normal life.", categories: ["weight-loss", "transformation", "identified"], rating: 5, imageUrl: "assets/images/transformations/t1.png", result: "15kg lost in 6 months", source: "Transformation client", avatarCrop: true, avatarPosition: "78% 18%", avatarSize: "260%" },
  { id: 29, name: "Mateo R.", text: "I wanted to look leaner without feeling weak. Andre adjusted the food and training gradually, and the progress photos helped me see what the scale did not show. The recomposition was exactly what I needed.", categories: ["body-recomp", "muscle-gain", "performance", "identified"], rating: 5, imageUrl: "assets/images/transformations/t2.2.png", result: "20% body fat reduction", source: "Transformation client", avatarCrop: true, avatarPosition: "72% 16%", avatarSize: "260%" },
  { id: 30, name: "Sofia L.", text: "The biggest win was not just losing 20kg. It was learning how to eat, train and recover in a way I could keep doing. Andre made the whole process feel structured instead of stressful.", categories: ["weight-loss", "lifestyle", "health", "identified"], rating: 5, imageUrl: "assets/images/transformations/t3.png", result: "20kg lost across 24 months", source: "Transformation client", avatarCrop: true, avatarPosition: "72% 18%", avatarSize: "260%" },
  { id: 31, name: "Maria C.", text: "At 60, I was worried training would hurt my joints. Andre adapted everything properly and still challenged me. I lost 13kg and feel stronger doing normal daily things.", categories: ["weight-loss", "health", "lifestyle", "identified"], rating: 5, imageUrl: "assets/images/transformations/t5.jpg", result: "13kg lost in 6 months", source: "Transformation client", avatarCrop: true, avatarPosition: "72% 14%", avatarSize: "260%" },
  { id: 32, name: "Liam B.", text: "Travel used to throw me off every time. The program gave me hotel-gym options, simple meal targets and a clear weekly reset. I finished 8kg down because the plan fit my schedule.", categories: ["weight-loss", "lifestyle", "transformation", "identified"], rating: 5, imageUrl: "assets/images/transformations/t6.jpg", result: "8kg lost in 12 weeks", source: "Transformation client", avatarCrop: true, avatarPosition: "75% 16%", avatarSize: "260%" },
  { id: 33, name: "Elena S.", text: "I did not want another quick diet. I wanted to feel athletic and confident. The strength work, protein targets and weekly adjustments helped me lose 8kg while building a better shape.", categories: ["body-recomp", "weight-loss", "muscle-gain", "identified"], rating: 5, imageUrl: "assets/images/transformations/t7.jpg", result: "8kg lost + muscle gained", source: "Transformation client", avatarCrop: true, avatarPosition: "74% 16%", avatarSize: "260%" },
  { id: 34, name: "Tom L.", text: "Every week had a clear target: train, eat, send the check-in, adjust. That consistency helped me lean out by 6kg while adding muscle, which I had never managed by myself.", categories: ["body-recomp", "muscle-gain", "performance", "identified"], rating: 5, imageUrl: "assets/images/transformations/t8.jpg", result: "6kg lost + 5% muscle increase", source: "Transformation client", avatarCrop: true, avatarPosition: "74% 15%", avatarSize: "260%" },
  { id: 35, name: "Renan P.", text: "I had a short deadline and needed precision. Andre set the training, hydration and food targets clearly, then adjusted based on the check-ins. I dropped 5kg in 20 days and still performed well.", categories: ["weight-loss", "performance", "body-recomp", "identified"], rating: 5, imageUrl: "assets/images/transformations/t14.jpg", result: "5kg lost in 20 days", source: "Transformation client", avatarCrop: true, avatarPosition: "74% 16%", avatarSize: "260%" },
  { id: 36, name: "Bianca M.", text: "Running a business made consistency difficult, but the daily targets were clear enough to follow. The check-ins were honest and practical. I lost 10kg in 12 weeks and kept my routine simple.", categories: ["weight-loss", "lifestyle", "transformation", "identified"], rating: 5, imageUrl: "assets/images/transformations/t16.jpg", result: "10kg lost in 12 weeks", source: "Transformation client", avatarCrop: true, avatarPosition: "74% 17%", avatarSize: "260%" },
  { id: 37, name: "Gabriel T.", text: "I did not want to sacrifice strength just to get lean. Andre managed the cut properly, watched the training numbers and adjusted when fatigue crept up. I finished 10kg lighter and still strong.", categories: ["weight-loss", "performance", "muscle-gain", "identified"], rating: 5, imageUrl: "assets/images/transformations/t17.jpg", result: "10kg cut in 16 weeks", source: "Transformation client", avatarCrop: true, avatarPosition: "74% 16%", avatarSize: "260%" },

  // Existing anonymous testimonials (10)
  { id: 16, name: "Anonymous", textKey: "testimonial.anon1", text: "Finally consistent after years of stops and starts.", categories: ["anonymous", "lifestyle"], rating: 5 },
  { id: 17, name: "Anonymous", textKey: "testimonial.anon2", text: "Clothes fit better and I feel lighter.", categories: ["anonymous", "weight-loss"], rating: 5 },
  { id: 18, name: "Anonymous", textKey: "testimonial.anon3", text: "Back pain gone, technique improved.", categories: ["anonymous", "health"], rating: 5 },
  { id: 19, name: "Anonymous", textKey: "testimonial.anon4", text: "Meal plan that works for me.", categories: ["anonymous", "health"], rating: 5 },
  { id: 20, name: "Anonymous", textKey: "testimonial.anon5", text: "Gained my first 5 pull-ups!", categories: ["anonymous", "muscle-gain"], rating: 5 },
  { id: 21, name: "Anonymous", textKey: "testimonial.anon6", text: "Down 7kg in 12 weeks without extremes.", categories: ["anonymous", "weight-loss"], rating: 5 },
  { id: 22, name: "Anonymous", textKey: "testimonial.anon7", text: "Better sleep and focus at work.", categories: ["anonymous", "health", "lifestyle"], rating: 5 },
  { id: 23, name: "Anonymous", textKey: "testimonial.anon8", text: "Stopped fearing carbs. Performance is up.", categories: ["anonymous", "performance"], rating: 5 },
  { id: 24, name: "Anonymous", textKey: "testimonial.anon9", text: "Program fits my travel schedule.", categories: ["anonymous", "lifestyle"], rating: 5 },
  { id: 25, name: "Anonymous", textKey: "testimonial.anon10", text: "Less joint pain, stronger lifts.", categories: ["anonymous", "performance", "health"], rating: 5 }
];
