// 25 testimonials: 15 identified and 10 anonymous.
// Each item: { id, name, text, textKey (for i18n), categories[], rating, imageUrl?, anonymous }

window.GB_TESTIMONIALS = [
  // Identified (15)
  { id: 1, name: "Conrad NorNam", textKey: "testimonial.conrad", text: "Andre rebuilt my training around 60-hour workweeks. We dropped 9kg of fat, added lean muscle, and my shoulders are pain-free for the first time in years.", categories: ["body-recomp", "muscle-gain", "identified"], rating: 5, imageUrl: "assets/images/avatars/conrad-2025.jpg" },
  { id: 2, name: "Lucas Almeida", textKey: "testimonial.lucas", text: "I tried every plan on my own and kept quitting after two weeks. Andre gave me structure, habits I could actually follow and honest feedback. I lost inches from my waist and, more importantly, I feel capable again.", categories: ["weight-loss", "transformation", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=300&h=300&fit=crop" },
  { id: 3, name: "Noah Williams", textKey: "testimonial.noah", text: "Sleep, stress, and steps became part of the plan. The holistic view is what finally made my results stick.", categories: ["lifestyle", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop" },
  { id: 4, name: "Arjun Mehta", textKey: "testimonial.arjun", text: "The technique cues on videos changed everything. I added 20kg to my squat while fixing depth and my knees feel great.", categories: ["muscle-gain", "performance", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=300&h=300&fit=crop" },
  { id: 5, name: "Mateo Gonzalez", textKey: "testimonial.mateo", text: "I lost 11kg without cutting entire food groups. The balanced approach removed the guilt and made weekends manageable.", categories: ["transformation", "weight-loss", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop" },
  { id: 6, name: "Jonas Muller", textKey: "testimonial.jonas", text: "The accountability made me show up even on tough weeks. I built routines that finally feel automatic.", categories: ["lifestyle", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop" },
  { id: 7, name: "James Walker", textKey: "testimonial.james", text: "As a busy dad I did not think I had time. Andre simplified training and I stuck with it.", categories: ["weight-loss", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop" },
  { id: 8, name: "Thiago Pereira", textKey: "testimonial.thiago", text: "I used to hide in baggy clothes. Twelve weeks later my friends keep asking what changed.", categories: ["transformation", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1531891570158-e71b35a485bc?w=300&h=300&fit=crop" },
  { id: 9, name: "Daniela Castro", textKey: "testimonial.daniela", text: "I appreciate the honest, data-driven approach. No gimmicks, just a plan tailored to me that I could actually follow.", categories: ["lifestyle", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop" },
  { id: 10, name: "Lucia Martinez", textKey: "testimonial.lucia", text: "After two pregnancies I thought my body would not respond. With gentle progressions and nutrition coaching, I am stronger and more confident than before.", categories: ["weight-loss", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop" },
  { id: 11, name: "Sophie Dubois", textKey: "testimonial.sophie", text: "Travel used to derail me. Now I land, check the plan and keep momentum. The flexibility is the reason I finally stayed consistent.", categories: ["lifestyle", "transformation", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop" },
  { id: 12, name: "Chi Nguyen", textKey: "testimonial.chi", text: "My blood pressure normalized and I have energy after work. Small daily habits were the difference maker for me.", categories: ["health", "lifestyle", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1544006659-f0b21884ce1d?w=300&h=300&fit=crop" },
  { id: 13, name: "Ana Morales", textKey: "testimonial.ana", text: "We fixed my shoulder impingement while building my first pull-up. Coaching is detailed and encouraging at the same time.", categories: ["muscle-gain", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop" },
  { id: 14, name: "Emma Johansson", textKey: "testimonial.emma", text: "I finally enjoy cooking again. The weekly recipes and shopping lists took away decision fatigue and helped me stay on track.", categories: ["weight-loss", "health", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=300&fit=crop" },
  { id: 15, name: "Sofia Martins", textKey: "testimonial.sofia", text: "Nutrition was always my struggle. Andre flexible approach removed guilt.", categories: ["health", "weight-loss", "identified"], rating: 5, imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=300&h=300&fit=crop" },

  // Anonymous (10)
  { id: 16, name: "Anonymous", textKey: "testimonial.anon1", text: "Finally consistent after years of stops and starts.", categories: ["anonymous", "lifestyle"], rating: 5 },
  { id: 17, name: "Anonymous", textKey: "testimonial.anon2", text: "Clothes fit better and I feel lighter.", categories: ["anonymous", "weight-loss"], rating: 5 },
  { id: 18, name: "Anonymous", textKey: "testimonial.anon3", text: "Back pain gone, technique improved.", categories: ["anonymous", "health"], rating: 5 },
  { id: 19, name: "Anonymous", textKey: "testimonial.anon4", text: "Meal plan that works for me.", categories: ["anonymous", "health"], rating: 5 },
  { id: 20, name: "Anonymous", textKey: "testimonial.anon5", text: "Gained my first 5 pull-ups!", categories: ["anonymous", "muscle-gain"], rating: 5 },
  { id: 21, name: "Anonymous", textKey: "testimonial.anon6", text: "Down 7kg in 12 weeks without extremes.", categories: ["anonymous", "weight-loss"], rating: 5 },
  { id: 22, name: "Anonymous", textKey: "testimonial.anon7", text: "Better sleep and focus at work.", categories: ["anonymous", "health", "lifestyle"], rating: 5 },
  { id: 23, name: "Anonymous", textKey: "testimonial.anon8", text: "Stopped fearing carbs. Performance is up.", categories: ["anonymous", "performance"], rating: 5 },
  { id: 24, name: "Anonymous", textKey: "testimonial.anon9", text: "Program fits my travel schedule.", categories: ["anonymous", "lifestyle"], rating: 5 },
  { id: 25, name: "Anonymous", textKey: "testimonial.anon10", text: "Less joint pain, stronger lifts.", categories: ["anonymous", "performance", "health"], rating: 5 }
];
