services:
  - type: web
    name: garcia-builder
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node api/stripe-server-premium.js
    autoDeploy: true
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
    healthCheckPath: /health
