name: Render Auto Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - 'render.yaml'
      - 'DEPLOY-TRIGGER.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secret
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "ERROR: Missing GitHub secret RENDER_DEPLOY_HOOK_URL" >&2
            echo "Add it in: Settings > Secrets and variables > Actions > New repository secret" >&2
            exit 1
          fi

      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Calling Render deploy hook..."
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_URL"
          echo "Render deploy hook fired successfully."

      - name: Log timestamp
        run: echo "Triggered at $(date -u) UTC"
